-- Sample seed data so the app is useful in local dev.
-- Replace with real curated club list before going to production.

insert into public.clubs (
  name, slug, description, year_founded, division, category,
  location, address_display, website_url, brand_color, status
) values
  (
    'Olympic Club RFC',
    'olympic-club-rfc',
    'A historic San Francisco rugby side competing at the highest level of US club rugby. Welcomes new players at all experience levels for the social side; the D1 squad is selective.',
    1981,
    'D1',
    'mens',
    st_makepoint(-122.4194, 37.7749)::geography,
    'San Francisco, CA',
    'https://www.olyclubrugby.com',
    '#B5161E',
    'approved'
  ),
  (
    'San Francisco Golden Gate RFC',
    'sf-golden-gate-rfc',
    'SFGG fields D1 men''s and women''s sides plus social and youth programs out of Treasure Island and the Presidio. Long-running pipeline to the Eagles.',
    1962,
    'D1',
    'mens',
    st_makepoint(-122.3712, 37.8235)::geography,
    'San Francisco, CA',
    'https://www.sfggrugby.org',
    '#1A1A1A',
    'approved'
  ),
  (
    'Berkeley All Blues',
    'berkeley-all-blues',
    'East Bay women''s rugby club with a deep tradition of national championships. Recruits experienced players and runs a strong development side.',
    1979,
    'D1',
    'womens',
    st_makepoint(-122.2730, 37.8715)::geography,
    'Berkeley, CA',
    null,
    '#003F87',
    'approved'
  ),
  (
    'San Jose Seahawks RFC',
    'san-jose-seahawks-rfc',
    'South Bay men''s side playing competitive Northern California club rugby. Friendly to new players and former high school / college athletes returning to the game.',
    1968,
    'D2',
    'mens',
    st_makepoint(-121.8863, 37.3382)::geography,
    'San Jose, CA',
    null,
    '#1A4D2E',
    'approved'
  );

-- Additional sample clubs spread across the US so the no-location map view
-- looks populated. All synthetic — replace with real curated data before prod.
insert into public.clubs (
  name, slug, description, year_founded, division, category,
  location, address_display, website_url, brand_color, status
) values
  -- Northeast
  (
    'Mystic River Rugby Club',
    'mystic-river-rugby',
    'Greater Boston men''s D1 side with an active D2 squad and a structured pathway for new and returning players.',
    1980,
    'D1',
    'mens',
    st_makepoint(-71.0589, 42.3601)::geography,
    'Boston, MA',
    null,
    '#0B3D91',
    'approved'
  ),
  (
    'Beantown RFC',
    'beantown-rfc',
    'Boston-based women''s rugby club with senior and developmental sides. Welcomes new players each season.',
    1976,
    'D1',
    'womens',
    st_makepoint(-71.0712, 42.3505)::geography,
    'Boston, MA',
    null,
    '#7B1B2E',
    'approved'
  ),
  (
    'Old Blue RFC of New York',
    'old-blue-rfc-new-york',
    'Manhattan-based club running multiple men''s sides through the year, from competitive D1 to social rugby.',
    1965,
    'D1',
    'mens',
    st_makepoint(-74.0060, 40.7128)::geography,
    'New York, NY',
    null,
    '#0D2B4F',
    'approved'
  ),
  (
    'Village Lions RFC',
    'village-lions-rfc',
    'New York City men''s club catering to working professionals; emphasizes social rugby alongside league play.',
    null,
    'D2',
    'mens',
    st_makepoint(-73.9857, 40.7308)::geography,
    'New York, NY',
    null,
    '#C29B0C',
    'approved'
  ),
  (
    'NYC Rugby Club',
    'nyc-rugby-club',
    'Established women''s rugby club fielding senior and developmental sides across all five boroughs.',
    1972,
    'D1',
    'womens',
    st_makepoint(-73.9442, 40.6782)::geography,
    'Brooklyn, NY',
    null,
    '#1E3A8A',
    'approved'
  ),
  (
    'Schuylkill River RFC',
    'schuylkill-river-rfc',
    'Philadelphia men''s rugby club with senior and developmental squads; trains year-round.',
    1969,
    'D2',
    'mens',
    st_makepoint(-75.1652, 39.9526)::geography,
    'Philadelphia, PA',
    null,
    '#1F4E2C',
    'approved'
  ),
  -- Mid-Atlantic / Southeast
  (
    'Washington Rugby Club',
    'washington-rugby-club',
    'D.C.-based men''s club fielding multiple sides through the league season; new players welcome at preseason.',
    1962,
    'D2',
    'mens',
    st_makepoint(-77.0369, 38.9072)::geography,
    'Washington, DC',
    null,
    '#7A1F1F',
    'approved'
  ),
  (
    'Potomac Exiles RFC',
    'potomac-exiles-rfc',
    'Northern Virginia men''s side with an emphasis on returning college players and seasoned veterans.',
    null,
    'D2',
    'mens',
    st_makepoint(-77.0910, 38.8816)::geography,
    'Arlington, VA',
    null,
    '#2A4D69',
    'approved'
  ),
  (
    'Atlanta Renegades RFC',
    'atlanta-renegades-rfc',
    'Atlanta men''s club with senior and developmental sides; runs preseason camps each summer.',
    1973,
    'D1',
    'mens',
    st_makepoint(-84.3880, 33.7490)::geography,
    'Atlanta, GA',
    null,
    '#3B0F0F',
    'approved'
  ),
  (
    'Charlotte Rugby Football Club',
    'charlotte-rfc',
    'Carolinas-area men''s club fielding multiple XVs and a regular Sevens program in summer.',
    1976,
    'D2',
    'mens',
    st_makepoint(-80.8431, 35.2271)::geography,
    'Charlotte, NC',
    null,
    '#0E4D7B',
    'approved'
  ),
  (
    'Tampa Krewe RFC',
    'tampa-krewe-rfc',
    'Gulf Coast men''s rugby club with a strong social side; trains year-round in Florida''s mild climate.',
    null,
    'D2',
    'mens',
    st_makepoint(-82.4572, 27.9506)::geography,
    'Tampa, FL',
    null,
    '#5D2F75',
    'approved'
  ),
  (
    'Miami Tridents RFC',
    'miami-tridents-rfc',
    'South Florida coed social club with regular touch and contact training; welcomes all skill levels.',
    null,
    'social',
    'mixed',
    st_makepoint(-80.1918, 25.7617)::geography,
    'Miami, FL',
    null,
    '#0E7C7B',
    'approved'
  ),
  -- Midwest
  (
    'Chicago Lions Rugby Club',
    'chicago-lions',
    'Chicago men''s rugby club with senior, developmental, and Sevens squads. Long pipeline of college recruits.',
    1965,
    'D1',
    'mens',
    st_makepoint(-87.6298, 41.8781)::geography,
    'Chicago, IL',
    null,
    '#7A0E0E',
    'approved'
  ),
  (
    'Chicago North Shore RFC',
    'chicago-north-shore-rfc',
    'North suburban Chicago women''s side with a strong development pathway from rookie to D1 starter.',
    null,
    'D2',
    'womens',
    st_makepoint(-87.6845, 42.0451)::geography,
    'Evanston, IL',
    null,
    '#13315C',
    'approved'
  ),
  (
    'Detroit Tradesmen RFC',
    'detroit-tradesmen-rfc',
    'Greater Detroit men''s club playing in the Midwest competition. Active recruitment each preseason.',
    1972,
    'D2',
    'mens',
    st_makepoint(-83.0458, 42.3314)::geography,
    'Detroit, MI',
    null,
    '#1F2937',
    'approved'
  ),
  (
    'Twin Cities Rugby',
    'twin-cities-rugby',
    'Minneapolis men''s rugby club with senior and second sides; welcomes returning college players.',
    1974,
    'D1',
    'mens',
    st_makepoint(-93.2650, 44.9778)::geography,
    'Minneapolis, MN',
    null,
    '#0F4D2E',
    'approved'
  ),
  (
    'Milwaukee Mongrels RFC',
    'milwaukee-mongrels-rfc',
    'Wisconsin men''s rugby club fielding XVs in the Midwest competition; strong social culture.',
    null,
    'D3',
    'mens',
    st_makepoint(-87.9065, 43.0389)::geography,
    'Milwaukee, WI',
    null,
    '#574B22',
    'approved'
  ),
  (
    'Kansas City Blues Rugby',
    'kansas-city-blues',
    'Kansas City men''s club with senior and Sevens programs; trains through Midwestern winters.',
    1965,
    'D1',
    'mens',
    st_makepoint(-94.5786, 39.0997)::geography,
    'Kansas City, MO',
    null,
    '#0F3B7A',
    'approved'
  ),
  (
    'Saint Louis Royals RFC',
    'st-louis-royals-rfc',
    'St. Louis men''s rugby club with multiple XVs and a youth development tie-in.',
    null,
    'D2',
    'mens',
    st_makepoint(-90.1994, 38.6270)::geography,
    'St. Louis, MO',
    null,
    '#5C2E91',
    'approved'
  ),
  -- South / Southwest
  (
    'Austin Huns RFC',
    'austin-huns-rfc',
    'Austin men''s rugby club with senior, developmental, and Sevens sides. Hosts an annual summer tournament.',
    1972,
    'D1',
    'mens',
    st_makepoint(-97.7431, 30.2672)::geography,
    'Austin, TX',
    null,
    '#7C2D12',
    'approved'
  ),
  (
    'Dallas Reds RFC',
    'dallas-reds-rfc',
    'Dallas men''s rugby club competing in the Red River league; runs structured rookie nights every season.',
    1968,
    'D1',
    'mens',
    st_makepoint(-96.7970, 32.7767)::geography,
    'Dallas, TX',
    null,
    '#9F1239',
    'approved'
  ),
  (
    'Houston Athletic Rugby Club',
    'houston-athletic-rugby',
    'Houston men''s side fielding XVs across senior and developmental squads; year-round training.',
    1971,
    'D2',
    'mens',
    st_makepoint(-95.3698, 29.7604)::geography,
    'Houston, TX',
    null,
    '#0E7490',
    'approved'
  ),
  (
    'New Orleans Rugby Football Club',
    'new-orleans-rfc',
    'NOLA-based coed social club running touch and contact rugby year-round.',
    null,
    'social',
    'mixed',
    st_makepoint(-90.0715, 29.9511)::geography,
    'New Orleans, LA',
    null,
    '#7E22CE',
    'approved'
  ),
  -- Mountain
  (
    'Denver Barbarians RFC',
    'denver-barbarians',
    'Denver men''s rugby club with senior and developmental sides; high-altitude preseason camp every August.',
    1967,
    'D1',
    'mens',
    st_makepoint(-104.9903, 39.7392)::geography,
    'Denver, CO',
    null,
    '#1A4D2E',
    'approved'
  ),
  (
    'Glendale Merlins RFC',
    'glendale-merlins',
    'Front Range men''s rugby club playing out of Infinity Park; structured pathway from rec to D1.',
    null,
    'D1',
    'mens',
    st_makepoint(-104.9333, 39.7058)::geography,
    'Glendale, CO',
    null,
    '#13606C',
    'approved'
  ),
  (
    'Salt Lake Lions RFC',
    'salt-lake-lions-rfc',
    'Utah men''s rugby club with senior and Sevens squads; recruits from local universities each fall.',
    null,
    'D2',
    'mens',
    st_makepoint(-111.8910, 40.7608)::geography,
    'Salt Lake City, UT',
    null,
    '#A16207',
    'approved'
  ),
  (
    'Phoenix RFC',
    'phoenix-rfc',
    'Greater Phoenix men''s side training year-round; partners with local schools on youth rugby clinics.',
    null,
    'D2',
    'mens',
    st_makepoint(-112.0740, 33.4484)::geography,
    'Phoenix, AZ',
    null,
    '#B45309',
    'approved'
  ),
  -- Pacific Northwest
  (
    'Seattle Saracens RFC',
    'seattle-saracens',
    'Seattle men''s rugby club with senior and developmental sides; longstanding rivalry with Portland.',
    1969,
    'D1',
    'mens',
    st_makepoint(-122.3321, 47.6062)::geography,
    'Seattle, WA',
    null,
    '#1E3A8A',
    'approved'
  ),
  (
    'Eastside Tsunami Rugby',
    'eastside-tsunami-rugby',
    'Greater Seattle women''s rugby club with structured rookie program and senior XV.',
    null,
    'D1',
    'womens',
    st_makepoint(-122.2015, 47.6101)::geography,
    'Bellevue, WA',
    null,
    '#0E7490',
    'approved'
  ),
  (
    'Portland Pigs RFC',
    'portland-pigs-rfc',
    'Portland men''s rugby club fielding multiple XVs; emphasizes inclusive culture across skill levels.',
    1973,
    'D2',
    'mens',
    st_makepoint(-122.6784, 45.5152)::geography,
    'Portland, OR',
    null,
    '#831843',
    'approved'
  ),
  -- Southern California
  (
    'Belmont Shore RFC',
    'belmont-shore-rfc',
    'Long Beach men''s D1 club with an active developmental side and Sevens program in summer.',
    1968,
    'D1',
    'mens',
    st_makepoint(-118.1937, 33.7701)::geography,
    'Long Beach, CA',
    null,
    '#0F172A',
    'approved'
  ),
  (
    'Old Mission Beach Athletic Club',
    'ombac-rugby',
    'San Diego men''s rugby club with multiple XVs and a Sevens program; hosts an annual summer tournament.',
    1968,
    'D1',
    'mens',
    st_makepoint(-117.1611, 32.7157)::geography,
    'San Diego, CA',
    null,
    '#172554',
    'approved'
  ),
  (
    'Pasadena RFC',
    'pasadena-rfc',
    'San Gabriel Valley men''s side fielding senior and developmental squads in Southern California Rugby.',
    null,
    'D2',
    'mens',
    st_makepoint(-118.1445, 34.1478)::geography,
    'Pasadena, CA',
    null,
    '#7C2D12',
    'approved'
  ),
  -- Youth
  (
    'Bay Area Youth Rugby',
    'bay-area-youth-rugby',
    'Coed youth program running U10–U18 contact and touch programs through fall and spring seasons.',
    null,
    'youth',
    'youth_mixed',
    st_makepoint(-122.2711, 37.8044)::geography,
    'Oakland, CA',
    null,
    '#15803D',
    'approved'
  ),
  -- New England fill-in
  (
    'Providence RFC',
    'providence-rfc',
    'Rhode Island men''s rugby club with senior and developmental sides; trains through New England winters.',
    null,
    'D2',
    'mens',
    st_makepoint(-71.4128, 41.8240)::geography,
    'Providence, RI',
    null,
    '#1E3A8A',
    'approved'
  ),
  (
    'Hartford Wanderers RFC',
    'hartford-wanderers-rfc',
    'Connecticut men''s side competing in the New England competition; structured rookie nights each preseason.',
    1971,
    'D2',
    'mens',
    st_makepoint(-72.6734, 41.7658)::geography,
    'Hartford, CT',
    null,
    '#7C2D12',
    'approved'
  ),
  (
    'Burlington Rugby Club',
    'burlington-rugby-club',
    'Northern Vermont coed social rugby club running touch and contact training through summer.',
    null,
    'social',
    'mixed',
    st_makepoint(-73.2121, 44.4759)::geography,
    'Burlington, VT',
    null,
    '#0E7490',
    'approved'
  ),
  (
    'Portland Maine Pioneers RFC',
    'portland-me-pioneers-rfc',
    'Coastal Maine men''s rugby club with a small but committed senior side and growing development squad.',
    null,
    'D3',
    'mens',
    st_makepoint(-70.2568, 43.6591)::geography,
    'Portland, ME',
    null,
    '#075985',
    'approved'
  ),
  -- Upstate / Western NY
  (
    'Buffalo Old Boys RFC',
    'buffalo-old-boys-rfc',
    'Western New York men''s club fielding XVs in the Empire competition; emphasizes social rugby alongside league play.',
    1968,
    'D2',
    'mens',
    st_makepoint(-78.8784, 42.8864)::geography,
    'Buffalo, NY',
    null,
    '#0F172A',
    'approved'
  ),
  (
    'Rochester Aardvarks RFC',
    'rochester-aardvarks-rfc',
    'Finger Lakes-area men''s rugby club with senior and developmental sides; trains year-round.',
    null,
    'D2',
    'mens',
    st_makepoint(-77.6088, 43.1566)::geography,
    'Rochester, NY',
    null,
    '#7C3AED',
    'approved'
  ),
  (
    'Army West Point Rugby',
    'army-west-point-rugby',
    'United States Military Academy collegiate men''s side; competes in the top tier of US college rugby.',
    null,
    'collegiate',
    'mens',
    st_makepoint(-73.9560, 41.3915)::geography,
    'West Point, NY',
    null,
    '#1F2937',
    'approved'
  ),
  -- Mid-Atlantic / Steel City
  (
    'Pittsburgh Harlequins',
    'pittsburgh-harlequins',
    'Western PA men''s D1 club with a long history of producing competitive sides; multiple XVs each season.',
    1969,
    'D1',
    'mens',
    st_makepoint(-79.9959, 40.4406)::geography,
    'Pittsburgh, PA',
    null,
    '#000000',
    'approved'
  ),
  (
    'Pittsburgh Angels Rugby',
    'pittsburgh-angels-rugby',
    'Pittsburgh women''s rugby club with senior and developmental squads; structured rookie program each fall.',
    null,
    'D1',
    'womens',
    st_makepoint(-80.0079, 40.4506)::geography,
    'Pittsburgh, PA',
    null,
    '#BE185D',
    'approved'
  ),
  (
    'Baltimore Chesapeake RFC',
    'baltimore-chesapeake-rfc',
    'Charm City men''s side fielding XVs in the Mid-Atlantic competition; recruits returning college players each fall.',
    null,
    'D2',
    'mens',
    st_makepoint(-76.6122, 39.2904)::geography,
    'Baltimore, MD',
    null,
    '#3F3F46',
    'approved'
  ),
  (
    'Navy Rugby',
    'navy-rugby',
    'United States Naval Academy collegiate men''s side; long-standing fixture in US college rugby.',
    null,
    'collegiate',
    'mens',
    st_makepoint(-76.4922, 38.9784)::geography,
    'Annapolis, MD',
    null,
    '#1E3A8A',
    'approved'
  ),
  -- Southeast fill-in
  (
    'Nashville Rugby Club',
    'nashville-rugby-club',
    'Middle Tennessee men''s rugby club with senior and Sevens programs; trains year-round.',
    null,
    'D2',
    'mens',
    st_makepoint(-86.7816, 36.1627)::geography,
    'Nashville, TN',
    null,
    '#7C2D12',
    'approved'
  ),
  (
    'Birmingham Vulcans RFC',
    'birmingham-vulcans-rfc',
    'Alabama men''s rugby club fielding senior and developmental XVs in the Deep South competition.',
    null,
    'D2',
    'mens',
    st_makepoint(-86.8104, 33.5186)::geography,
    'Birmingham, AL',
    null,
    '#9A3412',
    'approved'
  ),
  (
    'Orlando Rugby Club',
    'orlando-rugby-club',
    'Central Florida men''s side with senior and developmental squads; year-round outdoor training.',
    null,
    'D2',
    'mens',
    st_makepoint(-81.3792, 28.5383)::geography,
    'Orlando, FL',
    null,
    '#1E40AF',
    'approved'
  ),
  (
    'Raleigh Venom Rugby',
    'raleigh-venom-rugby',
    'Triangle-area women''s rugby club with senior and developmental sides; structured rookie program each fall.',
    null,
    'D2',
    'womens',
    st_makepoint(-78.6382, 35.7796)::geography,
    'Raleigh, NC',
    null,
    '#15803D',
    'approved'
  ),
  (
    'Jacksonville Axemen RFC',
    'jacksonville-axemen-rfc',
    'Northeast Florida men''s side fielding senior and developmental squads; emphasizes inclusive culture.',
    null,
    'D2',
    'mens',
    st_makepoint(-81.6557, 30.3322)::geography,
    'Jacksonville, FL',
    null,
    '#0F766E',
    'approved'
  ),
  -- Midwest fill-in
  (
    'Indianapolis Impalas RFC',
    'indianapolis-impalas-rfc',
    'Central Indiana men''s rugby club with senior and developmental sides; competes in the Midwest league.',
    null,
    'D2',
    'mens',
    st_makepoint(-86.1581, 39.7684)::geography,
    'Indianapolis, IN',
    null,
    '#0E7490',
    'approved'
  ),
  (
    'Columbus Rugby Club',
    'columbus-rugby-club',
    'Central Ohio men''s rugby club with senior and Sevens programs; recruits from local universities each fall.',
    1973,
    'D2',
    'mens',
    st_makepoint(-82.9988, 39.9612)::geography,
    'Columbus, OH',
    null,
    '#7F1D1D',
    'approved'
  ),
  (
    'Cleveland Crusaders RFC',
    'cleveland-crusaders-rfc',
    'Northeast Ohio men''s rugby club fielding XVs in the Midwest competition; active social side.',
    null,
    'D2',
    'mens',
    st_makepoint(-81.6944, 41.4993)::geography,
    'Cleveland, OH',
    null,
    '#451A03',
    'approved'
  ),
  (
    'Notre Dame Rugby',
    'notre-dame-rugby',
    'University of Notre Dame collegiate men''s rugby; competes in the top tier of US college rugby.',
    null,
    'collegiate',
    'mens',
    st_makepoint(-86.2520, 41.6764)::geography,
    'South Bend, IN',
    null,
    '#15803D',
    'approved'
  ),
  (
    'Madison Minotaurs RFC',
    'madison-minotaurs-rfc',
    'Wisconsin men''s rugby club with multiple XVs and a Sevens program; emphasizes social rugby culture.',
    null,
    'D3',
    'mens',
    st_makepoint(-89.4012, 43.0731)::geography,
    'Madison, WI',
    null,
    '#831843',
    'approved'
  ),
  -- Plains
  (
    'Oklahoma City Crusaders RFC',
    'okc-crusaders-rfc',
    'Central Oklahoma men''s rugby club with senior and developmental squads; trains year-round.',
    null,
    'D2',
    'mens',
    st_makepoint(-97.5164, 35.4676)::geography,
    'Oklahoma City, OK',
    null,
    '#7C2D12',
    'approved'
  ),
  -- Mountain fill-in
  (
    'Boise Pelicans RFC',
    'boise-pelicans-rfc',
    'Treasure Valley men''s rugby club with senior and developmental sides; outdoor training year-round.',
    null,
    'D3',
    'mens',
    st_makepoint(-116.2023, 43.6150)::geography,
    'Boise, ID',
    null,
    '#0E7490',
    'approved'
  ),
  (
    'Las Vegas Blackjacks RFC',
    'las-vegas-blackjacks-rfc',
    'Southern Nevada men''s rugby club fielding XVs and a Sevens side; hosts an annual desert Sevens tournament.',
    null,
    'D2',
    'mens',
    st_makepoint(-115.1398, 36.1699)::geography,
    'Las Vegas, NV',
    null,
    '#1F2937',
    'approved'
  ),
  (
    'BYU Rugby',
    'byu-rugby',
    'Brigham Young University collegiate men''s side; multi-time top-tier finisher in US college rugby.',
    null,
    'collegiate',
    'mens',
    st_makepoint(-111.6585, 40.2338)::geography,
    'Provo, UT',
    null,
    '#1E3A8A',
    'approved'
  ),
  -- California gap fill-in
  (
    'Sacramento Capitals RFC',
    'sacramento-capitals-rfc',
    'Greater Sacramento men''s rugby club with senior and developmental squads; trains year-round in NorCal.',
    null,
    'D2',
    'mens',
    st_makepoint(-121.4944, 38.5816)::geography,
    'Sacramento, CA',
    null,
    '#7C3AED',
    'approved'
  ),
  (
    'Sacramento Amazons',
    'sacramento-amazons',
    'NorCal women''s rugby club with senior and developmental sides; structured rookie program each season.',
    null,
    'D2',
    'womens',
    st_makepoint(-121.4944, 38.5816)::geography,
    'Sacramento, CA',
    null,
    '#BE185D',
    'approved'
  ),
  (
    'Orange County Rugby Football Club',
    'orange-county-rfc',
    'SoCal coastal men''s rugby club with senior and developmental squads; active Sevens program in summer.',
    null,
    'D2',
    'mens',
    st_makepoint(-117.9298, 33.6189)::geography,
    'Newport Beach, CA',
    null,
    '#9A3412',
    'approved'
  ),
  (
    'Santa Barbara Sharks RFC',
    'santa-barbara-sharks-rfc',
    'Central coast men''s rugby club fielding XVs in Southern California Rugby; emphasizes inclusive culture.',
    null,
    'D3',
    'mens',
    st_makepoint(-119.6982, 34.4208)::geography,
    'Santa Barbara, CA',
    null,
    '#0E7490',
    'approved'
  ),
  -- Hawaii outpost
  (
    'Honolulu Harlequins RFC',
    'honolulu-harlequins-rfc',
    'O''ahu men''s rugby club with senior and developmental sides; year-round island training.',
    null,
    'D2',
    'mens',
    st_makepoint(-157.8581, 21.3099)::geography,
    'Honolulu, HI',
    null,
    '#15803D',
    'approved'
  );
